version: '3.6'

services:
  db:
    image: postgres:12.6
    environment:
      POSTGRES_USER: read.exchange.admin
      POSTGRES_PASSWORD: admin@24
      POSTGRES_DB: read1

  backend:
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    build: ./docker/backend
    links:
      - db
    ports:
      - 8081:8081
    volumes:
      - ./backend:/app:cached
      - backend_node_modules_cache:/app/node_modules
    environment:
      DB_HOST: db

  frontend:
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    build: ./docker/frontend
    links:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules_cache:/app/node_modules
    # environment:
    #   HOST: localhost
    #   PORT: 3000

volumes:
  backend_node_modules_cache:
  frontend_node_modules_cache:
