# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
name: Test Backend

on:
  push:
    paths:
      - './backend'

env:
  NODE_VERSION: 16.x

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: actions/cache@v2.1.4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-backend-${{ hashFiles('**/npm.lock') }}
        restore-keys: |
          ${{ runner.os }}-npm-backend-
    - run: npm install
    - name: ESlint
      run: |
        npm run lint
